# Generated by Django 4.2.11 on 2026-04-15 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('category', models.CharField(choices=[('vegetables', '蔬菜'), ('fruits', '水果'), ('meat', '肉类'), ('seafood', '海鲜'), ('dairy', '乳制品'), ('grains', '谷物'), ('nuts', '坚果'), ('beverages', '饮料'), ('snacks', '零食'), ('other', '其他')], default='other', max_length=50, verbose_name='分类')),
                ('calories', models.FloatField(default=0, verbose_name='卡路里 (kcal/100g)')),
                ('protein', models.FloatField(default=0, verbose_name='蛋白质 (g/100g)')),
                ('carbs', models.FloatField(default=0, verbose_name='碳水化合物 (g/100g)')),
                ('fat', models.FloatField(default=0, verbose_name='脂肪 (g/100g)')),
                ('fiber', models.FloatField(default=0, verbose_name='膳食纤维 (g/100g)')),
                ('sugar', models.FloatField(default=0, verbose_name='糖 (g/100g)')),
                ('serving_size', models.FloatField(default=100, verbose_name='标准份量(g)')),
                ('serving_name', models.CharField(default='100g', max_length=50, verbose_name='份量名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '食物',
                'verbose_name_plural': '食物',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Meal', max_length=200, verbose_name='名称')),
                ('items', models.TextField(verbose_name='食物列表(JSON)')),
                ('total_weight', models.FloatField(default=0, verbose_name='总重量(g)')),
                ('total_calories', models.FloatField(default=0, verbose_name='总卡路里')),
                ('total_protein', models.FloatField(default=0, verbose_name='总蛋白质')),
                ('total_carbs', models.FloatField(default=0, verbose_name='总碳水')),
                ('total_fat', models.FloatField(default=0, verbose_name='总脂肪')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '计算历史',
                'verbose_name_plural': '计算历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
